### ISSUE TITLE
Old PyPI release

### ISSUE THREAD

**Issue by kdembler** [Infineon/BlockchainSecurity2Go-Python-Library#20]
Hey there!
Would it be possible to release new `blocksec2go` version to PyPI? The current one is from March and it seems there's been a number of changes since then. Examples included in the repo don't work with the PyPI version as it doesn't include `find_reader` method for example and it can be a bit confusing at first :)
Cheers!

**Comment by DhruvKhemani** [comment]
Can confirm, the version on PyPI is quite old. For now just clone the repo and manually install it via `pip install setup.py`... 😄

**Comment by WaltherPachler** [comment]
Hey there!
we made an update 😃 
BR
