### ISSUE TITLE
Old PyPI release

### ISSUE THREAD

**Issue by DhruvKhemani** [Infineon/BlockchainSecurity2Go-Python-Library#23]
Hey,
would it be possible to release a new blocksec2go version to PyPI? The version out of PyPI is 1.1 even though the repo is on 1.2. The observer example included in the repo doesn't work with the current PyPI version.
Thanks!

**Comment by WaltherPachler** [comment]
True that:

Traceback (most recent call last):
  File "praesidium.py", line 18, in <module>
    from blocksec2go.comm import observer
ImportError: cannot import name 'observer' from 'blocksec2go.comm' (C:\Users\Pachler\AppData\Local\Continuum\anaconda3\lib\site-packages\blocksec2go\comm\__init__.py)

we will update! :)

**Comment by DhruvKhemani** [comment]
Thank you for updating blocksec2go on PyPI!
